# Generated by Django 5.0.2 on 2024-02-16 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategoryModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Book_category_table',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'User_table',
            },
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='Media')),
                ('price', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.bookcategorymodel')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.usermodel')),
            ],
            options={
                'db_table': 'book_table',
            },
        ),
    ]
